baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "compose"

#  menu items
[[menu.main]]
    name = "Docs"
    weight = 2
    url = "docs/"

[[menu.main]]
    name = "Example"
    weight = 3
    url = "https://docs.neuralvibes.com"

    [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

    